laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('empresa/{secao?}', 'EmpresaController@index')->name('empresa');
    Route::get('servicos', 'ServicosController@index')->name('servicos');
    Route::get('projetos/{categoria?}', 'ProjetosController@index')->name('projetos');
    Route::get('clientes', 'ClientesController@index')->name('clientes');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato/contato', 'ContatoController@postContato')->name('contato.post-contato');
    Route::post('contato/fornecedor', 'ContatoController@postFornecedor')->name('contato.post-fornecedor');
    Route::post('contato/briefing', 'ContatoController@postBriefing')->name('contato.post-briefing');
    Route::post('contato/curriculo', 'ContatoController@postCurriculo')->name('contato.post-curriculo');
    Route::post('newsletter', 'NewsletterController@post')->name('newsletter.post');


    // Localização
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if ($idioma == 'pt' || $idioma == 'en') Session::put('locale', $idioma);
        return redirect()->back();
    })->name('lang');


    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('popup', 'PopupController', ['only' => ['index', 'update']]);
		Route::resource('depoimentos', 'DepoimentosController');
		Route::resource('perfil', 'PerfilController', ['only' => ['index', 'update']]);
		Route::resource('estrutura', 'EstruturaController');
		Route::resource('valores', 'ValoresController', ['only' => ['index', 'update']]);
		Route::resource('clientes', 'ClientesController');
		Route::resource('projetos', 'ProjetosController');
        Route::get('projetos/{projetos}/imagens/clear', [
            'as'   => 'painel.projetos.imagens.clear',
            'uses' => 'ProjetosImagensController@clear'
        ]);
        Route::resource('projetos.imagens', 'ProjetosImagensController');
		Route::resource('diferenciais', 'DiferenciaisController');
		Route::resource('historia', 'HistoriaController', ['only' => ['index', 'update']]);
		Route::resource('segmentos', 'SegmentosController');
		Route::resource('servicos', 'ServicosController', ['only' => ['index', 'update']]);
		Route::resource('banners', 'BannersController');
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato/fornecedores', 'FornecedoresRecebidosController');
        Route::resource('contato/curriculos', 'CurriculosRecebidosController');
        Route::resource('contato/briefings', 'BriefingsRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::get('newsletter/exportar', ['as' => 'painel.newsletter.exportar', 'uses' => 'NewsletterController@exportar']);
        Route::resource('newsletter', 'NewsletterController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('order', 'PainelController@order');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);
            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);
            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/BriefingsRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\BriefingRecebido;

class BriefingsRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = BriefingRecebido::orderBy('id', 'DESC')->paginate(15);

        return view('painel.contato.briefings.index', compact('contatosrecebidos'));
    }

    public function show(BriefingRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.briefings.show', compact('contato'));
    }

    public function destroy(BriefingRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.briefings.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ClientesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ClientesRequest;
use App\Http\Controllers\Controller;

use App\Models\Cliente;

class ClientesController extends Controller
{
    public function index()
    {
        $clientes = Cliente::ordenados()->get();

        return view('painel.clientes.index', compact('clientes'));
    }

    public function show(Cliente $cliente)
    {
        return $cliente;
    }

    public function store(ClientesRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = Cliente::upload_imagem();

            $cliente = Cliente::create($input);

            $view = view('painel.clientes.imagem', compact('cliente'))->render();

            return response()->json(['body' => $view]);

        } catch (\Exception $e) {

            return 'Erro ao adicionar imagem: '.$e->getMessage();

        }
    }

    public function destroy(Cliente $cliente)
    {
        try {

            $cliente->delete();
            return redirect()->route('painel.clientes.index')
                             ->with('success', 'Imagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir imagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('id', 'DESC')->paginate(15);

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/CurriculosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\CurriculoRecebido;

class CurriculosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = CurriculoRecebido::orderBy('id', 'DESC')->paginate(15);

        return view('painel.contato.curriculos.index', compact('contatosrecebidos'));
    }

    public function show(CurriculoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.curriculos.show', compact('contato'));
    }

    public function destroy(CurriculoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.curriculos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/DepoimentosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\DepoimentosRequest;
use App\Http\Controllers\Controller;

use App\Models\Depoimento;
use App\Helpers\Tools;

class DepoimentosController extends Controller
{
    public function index()
    {
        $registros = Depoimento::ordenados()->get();

        return view('painel.depoimentos.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.depoimentos.create');
    }

    public function store(DepoimentosRequest $request)
    {
        try {

            $input = $request->all();
            $input['capa'] = Tools::videoThumb($request->get('video_tipo'), $request->get('video_codigo'));

            Depoimento::create($input);

            return redirect()->route('painel.depoimentos.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Depoimento $registro)
    {
        return view('painel.depoimentos.edit', compact('registro'));
    }

    public function update(DepoimentosRequest $request, Depoimento $registro)
    {
        try {

            $input = $request->all();

            if ($input['video_codigo'] !== $registro->video_codigo || $input['video_tipo'] !== $registro->video_tipo) {
                $input['capa'] = Tools::videoThumb($input['video_tipo'], $input['video_codigo']);
            }

            $registro->update($input);

            return redirect()->route('painel.depoimentos.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Depoimento $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.depoimentos.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/DiferenciaisController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\DiferenciaisRequest;
use App\Http\Controllers\Controller;

use App\Models\Diferencial;

class DiferenciaisController extends Controller
{
    public function index()
    {
        $registros = Diferencial::ordenados()->get();

        return view('painel.diferenciais.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.diferenciais.create');
    }

    public function store(DiferenciaisRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Diferencial::upload_imagem();

            Diferencial::create($input);
            return redirect()->route('painel.diferenciais.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Diferencial $registro)
    {
        return view('painel.diferenciais.edit', compact('registro'));
    }

    public function update(DiferenciaisRequest $request, Diferencial $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Diferencial::upload_imagem();

            $registro->update($input);
            return redirect()->route('painel.diferenciais.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Diferencial $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.diferenciais.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/EstruturaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\EstruturaRequest;
use App\Http\Controllers\Controller;

use App\Models\Estrutura;

class EstruturaController extends Controller
{
    public function index()
    {
        $registros = Estrutura::ordenados()->get();

        return view('painel.estrutura.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.estrutura.create');
    }

    public function store(EstruturaRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Estrutura::upload_imagem();

            Estrutura::create($input);
            return redirect()->route('painel.estrutura.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Estrutura $registro)
    {
        return view('painel.estrutura.edit', compact('registro'));
    }

    public function update(EstruturaRequest $request, Estrutura $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Estrutura::upload_imagem();

            $registro->update($input);
            return redirect()->route('painel.estrutura.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Estrutura $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.estrutura.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
	<li @if(str_is('painel.popup*', Route::currentRouteName())) class="active" @endif>
		<a href="{{ route('painel.popup.index') }}">Popup</a>
	</li>
    <li @if(str_is('painel.banners*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.banners.index') }}">Banners</a>
    </li>
    <li class="dropdown @if(str_is('painel.historia*', Route::currentRouteName()) || str_is('painel.diferenciais*', Route::currentRouteName()) || str_is('painel.valores*', Route::currentRouteName()) || str_is('painel.estrutura*', Route::currentRouteName()) || str_is('painel.perfil*', Route::currentRouteName()) || str_is('painel.depoimentos*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Empresa
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li>
                <a href="{{ route('painel.historia.index') }}">História</a>
            </li>
            <li>
                <a href="{{ route('painel.diferenciais.index') }}">Diferenciais</a>
            </li>
            <li>
                <a href="{{ route('painel.valores.index') }}">Valores</a>
            </li>
        	<li>
        		<a href="{{ route('painel.estrutura.index') }}">Estrutura</a>
        	</li>
            <li>
                <a href="{{ route('painel.perfil.index') }}">Perfil</a>
            </li>
            <li>
                <a href="{{ route('painel.depoimentos.index') }}">Depoimentos</a>
            </li>
        </ul>
    </li>
    <li class="dropdown @if(str_is('painel.servicos*', Route::currentRouteName()) || str_is('painel.segmentos*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Serviços
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li>
                <a href="{{ route('painel.servicos.index') }}">Serviços</a>
            </li>
            <li>
                <a href="{{ route('painel.segmentos.index') }}">Segmentos</a>
            </li>
        </ul>
    </li>
    <li @if(str_is('painel.projetos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.projetos.index') }}">Projetos</a>
    </li>
	<li @if(str_is('painel.clientes*', Route::currentRouteName())) class="active" @endif>
		<a href="{{ route('painel.clientes.index') }}">Clientes</a>
	</li>
    <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos + $fornecedoresNaoLidos + $curriculosNaoLidos + $briefingsNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos + $fornecedoresNaoLidos + $curriculosNaoLidos + $briefingsNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ route('painel.contato.index') }}">Informações de Contato</a></li>
            <li class="divider"></li>
            <li><a href="{{ route('painel.contato.recebidos.index') }}">
                Contatos Recebidos
                @if($contatosNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                @endif
            </a></li>
            <li><a href="{{ route('painel.contato.fornecedores.index') }}">
                Fornecedores Recebidos
                @if($fornecedoresNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $fornecedoresNaoLidos }}</span>
                @endif
            </a></li>
            <li><a href="{{ route('painel.contato.curriculos.index') }}">
                Currículos Recebidos
                @if($curriculosNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $curriculosNaoLidos }}</span>
                @endif
            </a></li>
            <li><a href="{{ route('painel.contato.briefings.index') }}">
                Briefings Recebidos
                @if($briefingsNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $briefingsNaoLidos }}</span>
                @endif
            </a></li>
        </ul>
    </li>
    <li @if(str_is('painel.newsletter*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.newsletter.index') }}">Newsletter</a>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('site.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/bootstrap-toggle/css/bootstrap-toggle.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/painel/painel.css') }}">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url('/') }}">{{ config('site.name') }}</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                @include('painel.common.nav')

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName())) active @endif">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                            Sistema <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ route('painel.usuarios.index') }}">Usuários</a></li>
                            <li><a href="{{ route('logout') }}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{ asset("assets/vendor/jquery/dist/jquery.min.js") }}"><\/script>')</script>
    <script src="{{ asset('assets/vendor/bootswatch-dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/jquery-ui/jquery-ui.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/bootbox.js/bootbox.js') }}"></script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/vendor/bootstrap-toggle/js/bootstrap-toggle.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/blueimp-file-upload/js/jquery.fileupload.js') }}"></script>
    <script src="{{ asset('assets/painel/painel.js') }}"></script>
</body>
</html>